require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 9

Style/IfUnlessModifier:
  Enabled: false

Metrics/BlockLength:
  Max: 30

Style/RedundantConstantBase:
  Enabled: false
